### ISSUE TITLE
Performance degrades significantly with large cache sizes when cache fills up

### ISSUE THREAD

**Issue by JesseCrocker** [mojodna/tilelive-cache#11]
I've been using a 256mb cache size, and it appears that when the cache fills up cpu use doubles. Using a much smaller cache size, this doesn't happen.

Monitoring 10 ec2 instances running tessera, rendering vector tiles into rasters. The line that is consistently lower than the rest is using a cache size of 2mb, the rest are using 256. The times when another line is low, then climbs back up is when a new server comes up, or is restarted.
![screen shot 2016-10-14 at 12 52 54 pm](https://cloud.githubusercontent.com/assets/2048291/19399269/f4d1b06a-920d-11e6-9073-ce8c452d9702.png)

**Comment by mojodna** [comment]
Interesting... I'd expect that the CPU use is the result of [node-lru-cache](https://github.com/isaacs/node-lru-cache) doing housekeeping on cache fetches.

Swapping in [node-lru-native](https://github.com/adzerk/node-lru-native) might improve matters, but maybe that's thinking about the problem the wrong way.

Why is your cache size so large? Are you caching tiles as files elsewhere, or is this the primary caching implementation?

I originally added the cache as a way to shield sources from simultaneous reads of the same tile as well as to provide (some) benefit to metatiling (besides labeling improvements). Both of those use-cases only benefit from small caches.

I've been pondering filesystem overflow, i.e. writing to a sink and using that as a level 2 cache, for when tiles aren't being stored on, say, S3. This would be roughly equivalent to TileStache's caching mechanism, but with pluggable sinks. (POSM needs this, as the current style is slow to render and there's no caching infrastructure in front of it (Nginx would probably work, but I'm unclear on validation).)

(I even wrote [tilelive-leveldb](https://github.com/mojodna/tilelive-leveldb) with this in mind, as leveldb is quite a bit faster than SQLite (MBTiles) at the expense of not being easily distributable (since a leveldb is multiple files).

**Comment by JesseCrocker** [comment]
At this point i actually have no need for the cache to be that large. At one point my tile server cluster wasn't behind a CDN, so the the large cache size led to a high hit rate. But now it's behind a CDN, so the hit rate is 0, so I dropped the cache back to a very small value.

Im not looking for a fix for this issue, mostly just opened it for informational purposes.
