### ISSUE TITLE
callback.apply(callback, data)

### ISSUE THREAD

**Issue by wandergis** [mojodna/tilelive-cache#9]
cache is very useful,but when i work with a  mapnik xml, i got the error.
```javascript
Express server listening on port 8888
get tile 4, 13, 5
get tile 4, 12, 4
get tile 4, 12, 6
get tile 4, 14, 6
get tile 4, 14, 4
get tile 4, 11, 5
/Users/wandergis/Desktop/mapnik-demo/node_modules/tilelive-mapnik/lib/lockingcache.js:72
                callback.apply(callback, data);
                         ^

TypeError: Function.prototype.apply: Arguments list has wrong type
    at /Users/wandergis/Desktop/mapnik-demo/node_modules/tilelive-mapnik/lib/lockingcache.js:72:26
    at Array.forEach (native)
    at LockingCache.<anonymous> (/Users/wandergis/Desktop/mapnik-demo/node_modules/tilelive-mapnik/lib/lockingcache.js:71:23)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```

**Comment by mojodna** [comment]
This is a [tilelive-mapnik](https://github.com/mapbox/tilelive-mapnik) issue--have a closer look at the stack trace.

I've run into this before and _think_ that the root cause is metatile-related / related to the list of arguments changing before `process.nextTick`'s callback is run.

tilelive-cache works around this by bypassing tilelive-mapnik's internal cache (tiles would be double-cached otherwise): https://github.com/mojodna/tilelive-cache/blob/master/index.js#L244-L247

**Comment by wandergis** [comment]
thks very much.
